version: '3'

services:
  scooter-server:
    build:
      context: ./
      dockerfile: docker/scooters-api.Dockerfile
      platforms:
        - "linux/amd64"
    container_name: scooter-server
    ports:
      - "6000:6000"
    expose:
      - "6001"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    depends_on:
      - fluent-bit
    healthcheck:
      test: "grpcurl -plaintext scooter-server:6000 io.dmtri.scooters.service.ScootersApi.ping"
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s
    env_file:
      - ./.env
      - ./.env.secrets
  scooter-fake-client:
    build:
      context: ./
      dockerfile: docker/scooters-fake-client.Dockerfile
      platforms:
        - "linux/amd64"
    environment:
      - SERVER=grpc://scooter-server:6000
      - INTERVAL=1.0
      - MIN_SPEED=0.0
      - MAX_SPEED=8.33
      - BORDER_RADIUS=1000.0
    depends_on:
      scooter-server:
        condition: service_healthy
    deploy:
      replicas: 5
  fluent-bit:
    build:
      context: ./
      dockerfile: docker/fluent-bit.Dockerfile
      platforms:
        - "linux/amd64"
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluent-bit/plugins.conf:/fluent-bit/etc/plugins.conf
    env_file:
      - ./.env
      - ./.env.secrets
  prometheus-agent:
    build:
      context: ./
      dockerfile: docker/prometheus.Dockerfile
      platforms:
        - "linux/amd64"
    command: ["--enable-feature=agent"]
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
    env_file:
      - ./.env
      - ./.env.secrets
