version: '3'

services:
  scooter-server:
    build:
      context: ./
      dockerfile: docker/scooters-api.Dockerfile
    container_name: scooter-server
    ports:
      - "6000"
    expose:
      - 6000
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    depends_on:
      - fluent-bit
    env_file:
      - ./.env
      - ./.env.secrets
  scooter-fake-client:
    build:
      context: ./
      dockerfile: docker/scooters-fake-client.Dockerfile
    depends_on:
      - scooter-server
    environment:
      - server=grpc://scooter-server:6000
    volumes:
      - ./scooters-fake-client/.env:/.env
  fluent-bit:
    build:
      context: ./
      dockerfile: docker/fluent-bit.Dockerfile
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluent-bit/plugins.conf:/fluent-bit/etc/plugins.conf
    env_file:
      - ./.env
      - ./.env.secrets