version: '3'

services:
  scooter-server:
    build:
      context: ./
      dockerfile: docker/scooters-api.Dockerfile
    container_name: scooter-server
    ports:
      - "6000:6000"
    expose:
      - "6001"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    depends_on:
      - fluent-bit
    healthcheck:
      test: "grpcurl -plaintext scooter-server:6000 io.dmtri.scooters.service.ScootersApi.ping"
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s
    env_file:
      - ./.env
      - ./.env.secrets
  scooter-fake-client:
    build:
      context: ./
      dockerfile: docker/scooters-fake-client.Dockerfile
    environment:
      - server=grpc://scooter-server:6000
    volumes:
      - ./scooters-fake-client/.env:/.env
    depends_on:
      scooter-server:
        condition: service_healthy
    deploy:
      replicas: 5
  fluent-bit:
    build:
      context: ./
      dockerfile: docker/fluent-bit.Dockerfile
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluent-bit/plugins.conf:/fluent-bit/etc/plugins.conf
    env_file:
      - ./.env
      - ./.env.secrets
  prometheus:
    image: prom/prometheus
    command: ["--enable-feature=expand-external-labels"]
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
    env_file:
      - ./.env
      - ./.env.secrets
