version: '3'

services:
  scooter-fake-client:
    image: cr.yandex/crpvlbeg7ia4vj0j1o82/scooter-fake-client:${SCOOTER_FAKE_CLIENT_VERSION}
    environment:
      SERVER: ${SCOOTER_SERVER}
      INTERVAL: ${TELEMETRY_INTERVAL}
      MAX_SPEED: 20
      MIN_SPEED: 20
      MAP_SIZE: ${MAP_SIZE}
    deploy:
      replicas: 100
    restart: always